# Generated by Django 4.2.9 on 2024-04-18 13:16

from django.db import migrations, models
import django.db.models.deletion
import netbox_documents.utils
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0185_gfk_indexes'),
        ('extras', '0106_bookmark_user_cascade_deletion'),
        ('netbox_documents', '0007_circuitproviderdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPanelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(blank=True, upload_to=netbox_documents.utils.file_upload)),
                ('external_url', models.URLField(blank=True, max_length=255)),
                ('document_type', models.CharField(max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('powerpanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dcim.powerpanel')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Power Panel Document',
                'verbose_name_plural': 'Power Panel Documents',
                'ordering': ('name',),
            },
        ),
    ]
